### ISSUE TITLE
Missing dependencies.yaml

### ISSUE THREAD

**Issue by losuler** [gdrplatform/gDR#38]
Not sure if this is just a change in progress, but I wasn't able to create the Docker image without `rplatform/dependencies.yaml`, which appears to be missing in the `main` branch. Copying it from the latest active branch `GDR-1941`[^1] appeared to work.

[^1]: https://github.com/gdrplatform/gDR/blob/GDR-1941/rplatform/dependencies.yaml

**Comment by gladkia** [comment]
Hi, @losuler - thanks for your help. 

The issue has been fixed with https://github.com/gdrplatform/gDR/pull/40. The `rplatform/dependencies.yaml` is obsolete because we changed the logic. By default, we install the latest version of the packages from the Bioc/devel.
